version: '3.3'

volumes:
  fg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - fg_data:/var/lib/postgresql/data

  frontend:
    image: artyomserov/foodgram_frontend:v2
    container_name: frontend
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  backend:
    container_name: backend
    image: artyomserov/foodgram_backend:v2
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    command: >
      sh -c "sleep 12 && \
      python manage.py migrate && \
      python manage.py import_data && \
      python manage.py collectstatic --noinput && \
      cp -r /app/collected_static/. /backend_static/static/ && \
      gunicorn --bind 0.0.0.0:8000 foodgram.wsgi:application"

  nginx:
    image: artyomserov/foodgram_nginx:v2
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles
      - media:/media
      - ./backend/api/docs/:/usr/share/nginx/html/api/docs/