version: '3.3'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ../.env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  db:
    image: postgres:13.10
    container_name: db
    restart: always
    env_file:
      - ../.env
    volumes:
      - fg_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ../infra
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles

volumes:
  fg_data:
  static:
