# Generated by Django 4.2.3 on 2024-03-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': 'Ингредиент в рецептах', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
    ]
