# Generated by Django 4.2.16 on 2026-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredientinrecipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение для рецепта', max_length=200, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
