# Generated by Django 4.2.7 on 2023-12-03 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_slug",
                        message="Введите правильный slug.",
                        regex="^[-a-zA-Z0-9_]+$",
                    )
                ],
                verbose_name="Уникальный слаг",
            ),
        ),
    ]
