# Generated by Django 4.2.7 on 2023-12-21 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Количество не может быть меньше 1"
                    )
                ],
                verbose_name="Количество ингредиента",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1, message="Время должно быть больше 1 минуты"
                    )
                ],
                verbose_name="Время приготовления (в минутах)",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Выберите изображение для рецепта",
                upload_to="media/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                help_text="Укажите название блюда",
                max_length=200,
                verbose_name="Название рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата публикации"
            ),
        ),
    ]
