# Generated by Django 4.2.16 on 2026-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение для рецепта', max_length=200, upload_to='', verbose_name='Изображение'),
        ),
    ]
