# Generated by Django 4.2.7 on 2023-12-03 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Введите правильное имя пользователя.",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="Уникальный юзернейм",
            ),
        ),
    ]
