# Generated by Django 4.2.7 on 2024-01-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique follow",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="user",
            new_name="follower",
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("follower", "author"), name="unique follow"
            ),
        ),
    ]
