# Generated by Django 4.2.7 on 2024-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_follow_unique_follow_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique follow",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="follower",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="unique follow"
            ),
        ),
    ]
